name: release

on:
  push:
    branches:
      - release/prd

jobs:
  release:
    runs-on: ubuntu-18.04  # for install Wine
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"

      - name: Installing Wine...
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo apt install software-properties-common
          sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/ bionic main'
          wget -qO- https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key | sudo apt-key add -
          sudo sh -c 'echo "deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./" > /etc/apt/sources.list.d/obs.list'
          sudo apt update
          sudo apt-get install -y --install-recommends winehq-devel
          sudo apt-get install -y fakeroot

      - name: Building...
        env: 
          GH_TOKEN: ${{ secrets.github_token }}  # don't need to register anything to get PAT automatically
        run: |
          npm install
          npm run electron:build-for-github-actions

      - name: Make dirs...
        run: |
          mkdir ~/release/
          cp dist_electron/zenbu-hiraku_setup.exe ~/release/

      - name: Getting version from package.json...
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Creating a Tag...
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ steps.package-version.outputs.current-version}}"

      - name: Creating a Release...
        uses: ncipollo/release-action@v1
        with:
          artifacts: "~/release/*.exe"
          tag: "v${{ steps.package-version.outputs.current-version}}"
          token: ${{ secrets.github_token }}
