name: release

on:
  push:
    branches:
      - release/prd

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"

      - name: Building
        env: 
          GH_TOKEN: ${{ secrets.github_token }}  # don't need to register anything to get PAT automatically
        run: |
          npm install
          npm run electron:build-for-github-actions

      - name: Make dirs...
        run: |
          mkdir ~/release/
          cp dist_electron/ぜんぶひらく_Setup.exe ~/release/

      - name: Getting version from package.json...
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Creating a Tag...
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ steps.package-version.outputs.current-version}}"

      - name: Creating a Release...
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.package-version.outputs.current-version}}"
          token: ${{ secrets.github_token }}
          files: |
            ~/release/*.*
